"""Validate the locked build metadata and machine-readable run contract."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

EXPECTED_UV_VERSION = "0.11.29"
EXPECTED_PYTHON_FILE = "3.11"
EXPECTED_PYTHON_RANGE = ">=3.11,<3.14"
EXPECTED_SOLC = ["0.4.11", "0.4.16", "0.4.19", "0.7.6"]
REQUIRED_ENTRY_IDS = {
    "bootstrap-native",
    "smoke-native",
    "available-native",
}


def _normalized_export(text: str) -> str:
    """Ignore only uv's output-earing autogenerated command comment."""

    lines = text.replace("\r\n", "\n").replace("\r", "\n").splitlines()
    if len(lines) >= 2 and lines[0].startswith("# This file was autogenerated"):
        lines = lines[2:]
    return "\n".join(lines).rstrip() + "\n"


def _requirements_export_matches(root: Path) -> tuple[bool, str]:
    with tempfile.TemporaryDirectory(prefix="mpsc-lock-check-") as temp_dir:
        exported = Path(temp_dir) / "requirements-lock.txt"
        command = [
            "uv",
            "export",
            "--locked",
            "--all-extras",
            "--no-emit-project",
            "--format",
            "requirements-txt",
            "--output-file",
            str(exported),
        ]
        result = subprocess.run(
            command,
            cwd=root,
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        if result.returncode != 0:
            return False, (result.stdout + result.stderr).strip()
        tracked = (root / "requirements-lock.txt").read_text(encoding="utf-8")
        fresh = exported.read_text(encoding="utf-8")
        return (
            _normalized_export(tracked) == _normalized_export(fresh),
            "locked uv export matches requirements-lock.txt",
        )


def validate_build_contract(
    root: Path,
    *,
    check_export: bool = False,
) -> dict[str, object]:
    errors: list[str] = []
    checks: list[dict[str, str]] = []

    required = [
        ".python-version",
        "pyproject.toml",
        "uv.lock",
        "requirements-lock.txt",
        "BUILD_MATRIX.json",
        "ARTIFACT_MANIFEST.json",
    ]
    missing = [path for path in required if not (root / path).is_file()]
    if missing:
        errors.append("missing build inputs: " + ", ".join(missing))
    checks.append(
        {
            "name": "required-files",
            "status": "pass" if not missing else "fail",
            "detail": f"{len(required) - len(missing)}/{len(required)} present",
        }
    )
    if missing:
        return {
            "schema_version": 1,
            "status": "fail",
            "checks": checks,
            "errors": errors,
        }

    python_file = (root / ".python-version").read_text(encoding="utf-8").strip()
    project = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    uv_lock = (root / "uv.lock").read_text(encoding="utf-8")
    python_ok = (
        python_file == EXPECTED_PYTHON_FILE
        and project["project"]["requires-python"] == EXPECTED_PYTHON_RANGE
        and f'requires-python = "{EXPECTED_PYTHON_RANGE.replace(",", ", ")}"' in uv_lock
    )
    checks.append(
        {
            "name": "python-lock-range",
            "status": "pass" if python_ok else "fail",
            "detail": (
                f".python-version={python_file}; "
                f"project={project['project']['requires-python']}"
            ),
        }
    )
    if not python_ok:
        errors.append("Python baseline/range disagree across metadata and uv.lock")

    uv_result = subprocess.run(
        ["uv", "--version"],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    match = re.search(r"\buv\s+([0-9]+\.[0-9]+\.[0-9]+)\b", uv_result.stdout)
    actual_uv = match.group(1) if match else "unavailable"
    uv_ok = uv_result.returncode == 0 and actual_uv == EXPECTED_UV_VERSION
    checks.append(
        {
            "name": "uv-version",
            "status": "pass" if uv_ok else "fail",
            "detail": f"expected={EXPECTED_UV_VERSION}; actual={actual_uv}",
        }
    )
    if not uv_ok:
        errors.append(f"uv {EXPECTED_UV_VERSION} is required")

    matrix = json.loads((root / "BUILD_MATRIX.json").read_text(encoding="utf-8"))
    entry_ids = {item["id"] for item in matrix.get("entry_points", [])}
    matrix_ok = (
        matrix.get("schema_version") == 1
        and matrix.get("primary_environment", {}).get("uv") == EXPECTED_UV_VERSION
        and matrix.get("primary_environment", {}).get("solidity_compilers")
        == EXPECTED_SOLC
        and REQUIRED_ENTRY_IDS <= entry_ids
    )
    checks.append(
        {
            "name": "build-matrix",
            "status": "pass" if matrix_ok else "fail",
            "detail": f"entry_points={len(entry_ids)}",
        }
    )

    requirements = (root / "requirements-lock.txt").read_text(encoding="utf-8")
    hash_lock_ok = (
        "--hash=sha256:" in requirements
        and "\n-e " not in requirements
        and "git+https://" not in requirements
    )
    checks.append(
        {
            "name": "requirements-hash-lock",
            "status": "pass" if hash_lock_ok else "fail",
            "detail": (
                "hash-pinned portable export"
                if hash_lock_ok
                else "unsafe or unhashed requirements export"
            ),
        }
    )
    if not hash_lock_ok:
        errors.append("requirements-lock.txt is not a portable hash lock")

    if check_export:
        export_ok, export_detail = _requirements_export_matches(root)
        checks.append(
            {
                "name": "requirements-export",
                "status": "pass" if export_ok else "fail",
                "detail": export_detail,
            }
        )
        if not export_ok:
            errors.append(
                "requirements-lock.txt differs from the canonical locked uv export"
            )

    return {
        "schema_version": 1,
        "status": "pass" if not errors else "fail",
        "checks": checks,
        "errors": errors,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=Path("."))
    parser.add_argument("--check-export", action="store_true")
    args = parser.parse_args()
    result = validate_build_contract(
        args.project_root.resolve(),
        check_export=args.check_export,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result["status"] == "pass" else 1


if __name__ == "__main__":
    sys.exit(main())
